### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [NoG4Ek/ClassGraph#1]
✓ 0. Использование дефолтного пакета для размещения кода [is considered as a bad practice](https://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice);

✓ 1. Что-то пошло не так с областями видимости, как правило, методы объявляют как public (если они не содержат реализацию) - в расчете на программистов, которые будут использовать Ваш класс, а данные как private (+ генерируют get/set методы). Здесь надо либо поправить, либо быть готовым пояснить, почему Вы выбрали именно те модификаторы, которые выбрали;

✓2. Для методов вроде addVertex /delVertex ( аналоги add/remove) принято возвращать булевы величины, чтобы программист, использующий их, смог узнать результат выполнения вызова. Так сделано, например, в известном интерфейсе List. Здесь стоит четко разграничивать ситуации, в которых метод вызван в неподдерживаемых условиях от тех, когда его вызов разрешен (первое - исключение, второе - false; в Вашем случае это различие особо актуально для getIn/OutArcs -  трудно согласиться, что в ситуации, когда у вершины нет тех или иных дуг, методы должны именно выкидывать исключения - ситуация стандартная и должна быть предусмотрена). Для методов, работающих с Map, это могут быть предшествующие значения элементов по ключу/ null;

✓ 3. Относительно возвращаемых значений - стоит максимально стремиться сохранять структуру данных (так, например, в getIn/OutArcs стоит возвращать коллекции значений, а не строковое представление - потому что для того, чтобы им полноценно воспользоваться, в текущей версии его придется дополнительно парсить);

✓ 4. Для того, чтобы иметь возможность полноценно тестировать предложенную реализацию, необходимо переопределить метод equals. Также хорошим стилем является переопределение методов toString/hashCode (интерфейс Идеи предлагает возможность это сделать автоматизированно);

✓ 5. "/n" - не единственный вариант завершения строки. Для того, чтобы быть устойчивым к возможным переездам между разными версиями ОС, имеет смысл пользоваться, например, [методом System.lineSeparator()]https://www.dotnetperls.com/newline-java);

✓ 6. При объявлении переменных стремятся использовать максимально общие типы (Map вместо HashMap и т.д., только инициализируя реализацией интерфейса). Если Вы возвращаете просто Map, Вы не заставляете программиста - клиента использовать именно HashMap для хранения (например, если у него есть очень оптимизированный самописный Map, он выиграет). Ну, или ему просто удобнее применять другую реализацию. То же верно про ArrayList.  С точки зрения объявления - это просто про стиль;

**Comment by Suntrie** [comment]
0.  Про именование пакетов можно посмотреть, например, на официальном сайте oracle или [здесь](https://google.github.io/styleguide/javaguide.html);

1. Остаются вопросы по области видимости graph, startVertex - не вполне очевидно, почему она выбрана как package-private;

2.
   1. Формировать консольный вывод - не самое удачное решение (Вы разрабатываете класс, а не консольную программу). Если хочется каким-то образом логировать информацию независимо от слоя представления, можно попробовать делать это [так](https://stackoverflow.com/a/5950605);


   2. В addArc - с учётом того, что в map, который Вы изменяете, вы получили ссылку на мапу, лежащую под from - после того, как Вы её меняете, надо ли Вам её обратно засовывать put-ом или без этого можно обойтись?

   3. Хотела бы напомнить Вам [разницу между checked и unchecked exceptions](https://www.baeldung.com/java-checked-unchecked-exceptions). Вы точно в in/outArcs хотите "ломаться", не обязывая программиста предусматривать алгоритмы восстановления после поломки?

   4. `map.put(graph.get(from).keySet().toArray()[i], graph.get(from).get(graph.get(from).keySet().toArray()[i]));` - абсолютно нечитаемо, не надо так. В реальной жизни код читается немногим реже, чем пишется, он должен быть анализируемым;

3. Относительно возвратов пустых коллекций - в ситуациях, когда Вам нужно возвращать пустую коллекцию, Вам необходимо возвращать именно её. Тогда при вызове метода не придется бодаться со сравнением на null - можно просто проитерироваться по пустой коллекции 0 раз (на один "иф" меньше в клиентском коде);

4. toString куда-то потерялся.

**Comment by NoGe4Ek** [comment]
Почитал про наименование пакетов, но не понял, что не так

**Comment by Suntrie** [comment]
« Package names are written in all lower case to avoid conflict with the names of classes or interfaces. », « Package names are written in all lower case to avoid conflict with the names of classes or interfaces. » - не поняла, почему не поняли. Чем-то смертельным это, конечно, не является, просто отсылкой к общим стилевым аспектам языка. Обращаю Ваше внимание, что на вопросы по первому проекту я, по возможности, отвечать готова, но проверять его, поскольку оценка у Вас вроде как вполне положительная, готова буду только после  сдачи второго на уровень тройки и выше.
