### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by Suntrie** [NoG4Ek/ClassGraph#2]
✓ 1. С учетом количества методов, в которых Вы проходите по Map-у graph двойным for-ом, вытаскивая из списков, соответствующих аркам, элементы с совпадающим именем, модель данных кажется не самой удачной, возможно, стоит попробовать другие виды коллекций;

✓ 2. Что произойдет, если в changeName два имени совпадут?

3. Поправьте меня, пожалуйста, но текущая реализация addArc позволяет существовать нескольким несвязанным графам в graph (так быть не должно);

✓ 4. С точки зрения проектирования остается под большим вопросом актуальность выноса проверки на null в отдельный класс.

**Comment by NoGe4Ek** [comment]
Честно говоря 3 замечание довольно сильно усложняет задание. Могу предположить, что пользователь не будет делать таких графов 🙃. Иначе придется следить за тем, чтобы при удалении вершин или дуг граф случайно не разорвался (Частично это было исправлено, и создать ИЗНАЧАЛЬНО второй граф, который не будет связан с первым, не получится)

**Comment by Suntrie** [comment]
Вопрос для changeName все ещё актуален. remove по oldName в случае совпадения по newName даст удаление ситуации для newName.

**Comment by NoGe4Ek** [comment]
Не понимаю в чем проблема, если создать вершину с именем, которое уже существует, просто невозможно. Сменить имя на уже существующее тоже не получится.

**Comment by Suntrie** [comment]
Да, указанная ситуация действительно иметь место быть не может, спасибо, что обратили моё внимание. Это вроде даёт Вам прибавку в 0.25 к текущему результату (итого 4.25). Если хотите, чтобы я посмотрела текущую версию кода для того, чтобы улучшить результат - повторюсь, готова, но после того, как будет сдана с положительным результатом вторая работа.
